repos:
  - repo: https://github.com/Quantco/pre-commit-mirrors-black
    rev: 19.10b0
    hooks:
      - id: black-conda
        args:
          -   --safe
          -   --target-version=py38
  - repo: https://github.com/Quantco/pre-commit-mirrors-isort
    rev: ''
    hooks:
    - id: isort-conda
      additional_dependencies: [toml]
  - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
    rev: v3.8.4
    hooks:
      - id: flake8-conda
        args:
          -   --max-line-length=88
  - repo: https://github.com/Quantco/pre-commit-mirrors-mypy
    rev: "0.910"
    hooks:
        - id: mypy-conda
          additional_dependencies: [-c, conda-forge, types-setuptools]
  - repo: https://github.com/Quantco/pre-commit-mirrors-pyupgrade
    rev: 2.18.3
    hooks:
      - id: pyupgrade-conda