name: anchorboosting
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.9
  - pytest
  - numpy >=1.19.0
  - scipy
  - matplotlib
  - lightgbm >=4.0.0
  - pip
  - setuptools
  - pytest-cov
  - scikit-learn